#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_all(
       KC_Q,       KC_W, KC_F, KC_P,       KC_L, KC_U, KC_Y,       KC_J,
    KC_X, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O,KC_QUOT,
LCTL_T(KC_Z),KC_V, KC_C, KC_D, KC_B,       KC_K, KC_H, KC_COMM,KC_DOT,RCTL_T(KC_SLSH),

    KC_LGUI,KC_LALT,KC_LSFT,MO(1),KC_BSPC,KC_UNDS,LT(2,KC_TAB),KC_SPC,RALT_T(KC_GRV),KC_RGUI
    ),
    [1] = LAYOUT_all(
    KC_TILD,KC_LPRN,KC_RPRN,KC_DLR,             KC_7, KC_8, KC_9,       KC_COLN,
KC_PERC,KC_EXLM,KC_LT,KC_EQL,KC_GT,KC_AMPR,KC_ASTR,KC_4, KC_5, KC_6,KC_MINS,KC_CIRC,
LCTL_T(KC_LBRC),KC_LCBR,KC_RCBR,KC_RBRC,KC_PIPE,KC_PLUS,KC_1,KC_2,KC_3,RCTL_T(KC_BSLS),

KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,  KC_UNDS,LT(2,KC_SCLN),KC_0,KC_UNDS,RGUI_T(KC_DOT)
    ),
    [2] = LAYOUT_all(
    KC_F1,      KC_F2, KC_F3, KC_F4,        KC_HOME, KC_UP, KC_END, KC_VOLU,
KC_PSCR,KC_ESC,KC_INS,KC_BSPC,KC_DEL,KC_ENT,KC_PGUP,KC_LEFT,KC_DOWN,KC_RGHT,KC_VOLD,KC_MUTE,
LCTL_T(KC_F5),KC_F6,KC_F7,KC_F8,KC_APP,     KC_PGDN,KC_F9,KC_F10,KC_F11,RCTL_T(KC_F12),

    KC_LGUI,KC_LALT,KC_LSFT,MO(1),KC_BSPC,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_CALC
    )
};
